server:
  port: 8080

spring:
  application:
    name: medapp-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/medapp}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.medapp: DEBUG

jwt:
  secret: "une-cle-suffisament-longue-pour-hs256-en-dev"
  expiration-ms: 1800000 #30 minutes(access token)
  refresh-expiration-ms: 604800000  #7 jours (refresh token)
